### PR TITLE
[7.7.x] JBPM-7382 - Process model SVG is not updated in Windows environments

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@LuboTerifaj when testing locally building jbpm-designer and workbench 7.7.x (builds Version 7.7.1-SNAPSHOT) I am not getting this message. Could you try maybe delete your wildfly .index and .niogit in /bin directory before tests? I cant see this unfortunately. Thanks.

**Comment by tsurdilo** [comment]
@LuboTerifaj any update on this? I tried several times locally and not getting that issue you are mentioning.

**Comment by LuboTerifaj** [comment]
Hi @tsurdilo 
We had a public holiday in Czech on Thursday and Friday and it is taking more time to test it on Windows than I was expecting. I am going to test it again.

**Comment by LuboTerifaj** [comment]
Hi @tsurdilo 
I am still getting the same error. I have also tried to delete .niogit and .index files, but it didn't help. I am using 7.7.1-SNAPSHOT version as well. I am running business-central in Wildfly 11.0.0 on Windows. Here you can see screen-shot about error I am getting:
screenshot from 2018-07-10 11-47-51

**Comment by LuboTerifaj** [comment]
@tsurdilo 
I have tried it also on Linux and it seems that issue is also present on Linux. Do you want to fix it or should I open Jira for that? You can merge this PR then.

**Comment by tsurdilo** [comment]
@LuboTerifaj yes lets do thay - open a new jira so i can investigate why this is happening. Thanks

**Pull request merged**
