### PR TITLE
JBPM-7386 - Add support for BPMNDiagram resolution attribute

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@LuboTerifaj Hi, would you mind having a look please? 
This adds support for resolution property of BPMNDiagram bpmn2 node. 
How to test:
1. Get the attached bpmn2 process from https://issues.jboss.org/browse/BAPL-973
2. Import this bpmn2 into designer (nav bar -> import from bpmn2 - > paste that process)
3. Once imported designer now should apply the resolution property and zoom out so that the attached process looks like this:

screen shot 2018-07-02 at 1 04 34 pm


Existing or new processes created in designer have the resolution property set to 0 so no changes there. This is only for processes imported from other editors like ARIS. That one uses resolution property and via https://issues.jboss.org/browse/BAPL-973 it was requested that when those processes are imported into designer the resolution property is looked at.

**Comment by LuboTerifaj** [comment]
Hi @MarianMacik 
Can you have a look at this, since there are new teams?

**Comment by MarianMacik** [comment]
@LuboTerifaj Hi, unfortunately my knowledge with the designer code is quite limited :(

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@LuboTerifaj thanks, I was able to reproduce that as well (does not happen always tho). Given the huge size of the sample process nodes were not movable. I have reduced the amount of zoom that happens given the resolution and it should be better now. Please give it another try. Thanks.

Here is what the process after import should look like
screen shot 2018-07-16 at 5 18 25 pm

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Hey @tsurdilo 
Can you rebase it? This branch has conflicts.
Thanks.

**Comment by tsurdilo** [comment]
@LuboTerifaj rebased

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Hi @tsurdilo 

What's the status of this PR?

Do you plan to fix the issue mentioned above or do you want to close it?

Thank you.

**Comment by tsurdilo** [comment]
@LuboTerifaj I will fix it. just having to think of a different implementation that does not rely on zooming. Will update when i have something.

**Comment by ibek** [comment]
@tsurdilo how does it look? anywhere close to be done?

**Comment by tsurdilo** [comment]
@ibek @LuboTerifaj Updated this pr to not use zoom but adjust the x/y width/height bpmn di info as shown by @ibek in his email. This seems to be working much better and the uploaded process looks like:

screen shot 2018-10-02 at 8 54 59 am


Feel free to retest locally @LuboTerifaj . Thanks.

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@LuboTerifaj could you please share the bpmn2 you were testing with? it would help me fix this and having something to test with is really helpful. Thanks!

**Comment by tsurdilo** [comment]
@LuboTerifaj the issue with boundary events is something I can fix (and yes it is an issue). The thing about gateway/events sizes sorry but I cant. This issue does not break the validity of the bpmn2 so maybe its not urgent. Currently in designer gateways/event nodes are not resizeable and adding that would be huge and designer is maintenance..so I don't think we should attempt to do that at this point.

Working on boundary events and should have it done soon I hope.

**Comment by tsurdilo** [comment]
@LuboTerifaj updated the pr for fix for boundary events. The issue is that the ARIS bpmn2 does not give me any indication at what location this boundary event is "snapped" on so I can just guess and chose upper-left corner of the task its attached to. Might not be best place but user can after import easily just move the boundary events to the desired location but important thing is that the integrity of the boundary event is preserved (where before what you have seen it was not even considered as boundary).

Hope this is acceptable now.

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@LuboTerifaj The problem is that the resolution element value is a number, for example "245" - what does this number mean? This is not clear because it relates to the editor where this number is created. It could mean centimeters, pixels, inches, tomatoes ? :)

I have done best I could to apply it to bounds of elements given the bpmn2 Aris generates and given the jbpm-designer capabilities. Looked at the boundary location again and its just not available in the provided Aris bpmn2.

**Comment by ibek** [comment]
Yes please, lets merge it ... the important thing is that the imported process stays bpmn-valid and any alterations can be manually fixed if needed.

Thanks

**Pull request merged**
