### PR TITLE
JBPM-6274 - Update batik to 1.9 for master branch

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by mareknovotny** [comment]
It seems that  org.apache.xmlgraphics:batik-extension:jar is not managed in IP-BOM correctly, it contains instead **batik-ext**

We need to fix that first in IP BOM
``` 
[ERROR] 'dependencies.dependency.version' for org.apache.xmlgraphics:batik-extension:jar is missing. @ org.jbpm:jbpm-designer-backend:[unknown-version], /home/jenkins/workspace/jbpm-designer-pullrequests/jbpm-designer-backend/pom.xml, line 248, column 17
```

**Comment by mareknovotny** [comment]
I may be wrong on first view, but is `batik-ext` needed for jbpm-designer? 
I saw at some point they were both in pom.xml, but now it is only `batik-extension`,

**Comment by tsurdilo** [comment]
@mareknovotny after checking it seems neither are actually needed. I removed them and also added needed exclude for banned jar (pr amended). Thanks!

**Comment by mareknovotny** [comment]
@tsurdilo great! That is even better than I thought.

Now there are some enforcer warnings for duplicated classes in 4 dependencies
* `org.apache.xmlgraphics:batik-js:jar:1.7:compile` vs. `org.mozilla:rhino:jar:1.7R4:compile`
* `avalon-framework:avalon-framework:jar:4.1.4:compile` vs `org.apache.avalon.framework:avalon-framework-impl:jar:4.3.1:compile`
* `xml-apis:xml-apis:jar:1.4.01:compile` vs. `org.apache.xmlgraphics:batik-ext:jar:1.7:compile`
* `org.apache.avalon.framework:avalon-framework-api:jar:4.3.1:compile` vs. `avalon-framework:avalon-framework:jar:4.1.4:compile`

**Comment by tsurdilo** [comment]
@mareknovotny sorry after looking at the tests some more the 
org.apache.xmlgraphics:batik-extension
is indeed needed :( (not the batik-ext tho)
so we really need to add that depends into the ipbom.

I have updated this pr to include this depends and with the addition of batik-extension this pr compiles without issues. 
sorry again. thanks.

**Comment by tsurdilo** [comment]
@mareknovotny i think i found one more issue -- for designer tests to compile we need to up the version of 
version.org.apache.xmlgraphics.common to 2.0 (or higher) as that is when the class 
org.apache.xmlgraphics.java2d.color.NamedColorSpace is included there
which is needed at runtime for the png generation for designer.

**Comment by mareknovotny** [comment]
@tsurdilo  ok, that seems like we need to declare it too for it to be transparent, right as `org.apache.xmlgraphics.commons:xmlgraphics-commons` is transitive deps

Right now there is https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/604 which removes batik dependency management and keep them only in IP-BOM, so it seems to me that we need to move that `xmlgraphics-commons` with that change as splitting is troublesome for current layout of BOMs.

@mbiarnes, please can you remove the xmlgraphics-commons from your PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/604 too and I will sent IP-BOM update with inclusion of xmlgraphics-commons?

**Comment by tsurdilo** [comment]
we should ask jenkins to retest this pr once https://github.com/jboss-integration/jboss-integration-platform-bom/pull/409 is committed

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by mareknovotny** [comment]
Jenkins please retest

**Comment by tsurdilo** [comment]
@mareknovotny i think now we need to wait for https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/604  :) sorry i did not realize that was not merged

**Comment by tsurdilo** [comment]
@mareknovotny tell me please if im wrong but without https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/604 merged the changes to the ipbom regarding the commons lib update will never get picked up and designer will still use the 1.4 version specified in the build-bootstrap?

**Comment by tsurdilo** [comment]
also depends on changes in https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/604 specifically 

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/604/files#diff-600376dffeb79835ede4a0b285078036L94

so the 2.2 version is received from the ipbom

**Comment by mareknovotny** [comment]
@tsurdilo  yes, you are right, unfortunately i don't have merge permission so we need to ask someone who can do it

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
@mareknovotny ok now we depending on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/624

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
waiting on https://github.com/kiegroup/droolsjbpm-integration/pull/1294

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
@mareknovotny @psiroky I think we are good to go finally :) could please one of you guys approve? Thanks.

**Comment by mareknovotny** [comment]
@tsurdilo great news, I think it is good to go.

**Pull request merged**
