### PR TITLE
[6.5.x] JBPM-5995 - Missing icon in WID cause that task is not shown in Desig…

### PR DESCRIPTION
**Pull request by tsurdilo**
…ner (#603)

### CODE REVIEW

**Comment by tsurdilo** [comment]
@jomarko 6.5.x pr for https://issues.jboss.org/browse/RHBPMS-4991

**Comment by jomarko** [comment]
@tsurdilo thanks for backport, I will have a look.

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@jomarko full downstream build fail is not related to these changes. Can we merge?

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by jomarko** [comment]
@tsurdilo yes, I think we can merge.

**Pull request merged**
