### PR TITLE
JBPM-6457 - Variables with same name but in different scopes causes I…

### PR DESCRIPTION
**Pull request by tsurdilo**
…llegalArgumentExceptions by XmlParser

### CODE REVIEW

**Comment by tsurdilo** [comment]
@hasys @mswiderski Could you guys take a look pls? This just looks at existing process vars to make sure there are no duplicates.

**Comment by tsurdilo** [comment]
@hasys could you please take a look ?

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @tsurdilo, I already reviewed this changes in related PR: https://github.com/kiegroup/kie-wb-common/pull/1195

**Pull request merged**
