### PR TITLE
[BPMSPL-744] GIT related enhancements for scalable workspaces

### PR DESCRIPTION
**Pull request by ederign**
JGITFS support for multiple and scalable FS
    (prerequisite for workspaces and cloud)
    Also:
    [AF-573] Refactoring in order to centralize FileSystem Calls
    [AF-569] Cleanup and simplify clustering

### CODE REVIEW

**Comment by ederign** [comment]
Depends on https://github.com/AppFormer/uberfire/pull/797

**Comment by ederign** [comment]
jenkins retest this

**Comment by ederign** [comment]
jenkins retest this

**Comment by krisv** [comment]
@ederign just a recommendation for the naming, please don't (only) use BPMSPL JIRAs in there in the future, as these are not publicly visible to everyone, please create community JIRAs if appropriate

**Comment by tsurdilo** [comment]
@ederign can/should this be merged?

**Comment by tsurdilo** [comment]
@ederign should this be merged? thanks

**Pull request closed without merging**
