### PR TITLE
BAPL-764-migration-tool: Provide migration path from old Form Modeler to the new one

### PR DESCRIPTION
**Pull request by pefernan**
There has been some packages changes.

@tsurdilo could you please review?

This PR is part of an ensemble, merge with:

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/720
https://github.com/kiegroup/kie-wb-common/pull/1492
https://github.com/kiegroup/jbpm-designer/pull/754
https://github.com/kiegroup/jbpm-wb/pull/993
https://github.com/kiegroup/kie-wb-distributions/pull/704

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
@pefernan can this be merged?

**Comment by pefernan** [comment]
@tsurdilo not yet, waiting for some reviews in other modules. Thank you for being so fast looking into this ;)

**Pull request merged**
