### PR TITLE
JBPM-5975 - Enumerations can't be used as predefined values

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@hasys here is how to test -- i will add screenshots for specific steps in consequent comments:
********
1. Create new project
2. Go to "Artifact Repository"
3. Upload jar containing the Java annotation (the one from the jira you uploaded is good)
4. In project go to Settings -> Dependencies list and add new dependency
5. Enter GAV settings for dependency that match the pom generated when your jar was uploaded
6. Make sure in package white list "all packages included" is default selected and Save
7. create your business process with Email task
8. edit workitem definition and change the email definition to be (note customEditor is no longer neeed!):

[
    "name" : "Email",
    "parameters" : [
      "From" : new StringDataType(),
      "To" : new StringDataType(),
      "Subject" : new StringDataType(),
      "Body" : new StringDataType()
    ],
    "parameterValues" : [
         "From": "CarDealer,CarSeller,CarRepairman",
        "Subject" : new EnumDataType("wid.demo.CarsEnum")
    ],
    "displayName" : "Email",
    "icon" : "defaultemailicon.gif"
  ]

also dont forget to add the import
import org.drools.core.process.core.datatype.impl.type.EnumDataType;

9. Save wid and reopen business process
10. Click on email task and select Data IO editor (assignments property)
11. make sure that both From and Subject contains the parameter values (string based and from wid.demo.CarsEnum)
**********

**Comment by tsurdilo** [comment]
screen shot 2017-06-21 at 9 11 26 pm

**Comment by tsurdilo** [comment]
screen shot 2017-06-21 at 9 14 23 pm

**Comment by tsurdilo** [comment]
screen shot 2017-06-21 at 9 21 51 pm

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@hasys added changes that fix things after changes introduced in DROOLS-1608. We will add in jbpm a fix where users will not have to update all their wid imports but when testing this until this fix is in jbpm you will have to in your wid you are testing with change all imports from 

org.drools.core.process.core.datatype.impl.type.*
to
org.jbpm.process.core.datatype.impl.type.*

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
jBPM Workbench - Showcase module is failing on jenkins but is resolved so we can rebuild this pr soon hopefully build will be green

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@hasys now fail is on jBPM Workbench - Dashboard Client  module :)

**Comment by hasys** [comment]
@tsurdilo, yes, you are right :) Fix on the way: https://github.com/kiegroup/jbpm-wb/pull/771

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
rebased vs master branch

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@hasys test fail on org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromCustomRepository. Has not to do w/ these changes. Is it necessary that fails in other modules continue to delay testing of this change?

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@hasys yay finally green ;)

**Pull request merged**
