### PR TITLE
[BPMSPL-744] GIT related enhancements for scalable workspaces

### PR DESCRIPTION
**Pull request by ederign**
JGITFS support for multiple and scalable FS
    (prerequisite for workspaces and cloud)
    Also:
    [AF-573] Refactoring in order to centralize FileSystem Calls
    [AF-569] Cleanup and simplify clustering

depends on: https://github.com/AppFormer/uberfire/pull/881

### CODE REVIEW

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by ederign** [comment]
jenkins retest this

**Comment by ederign** [comment]
jenkins retest this

**Comment by ederign** [comment]
jenkins retest this

**Comment by ederign** [comment]
jenkins retest this

**Comment by tsurdilo** [comment]
+1 -- @ederign is this ok to be merged now ?

**Pull request merged**
