### PR TITLE
JBPM-6894 - User should be able to define case, process, activity lev…

### PR DESCRIPTION
**Pull request by mswiderski**
…el SLA

depends on https://github.com/kiegroup/droolsjbpm-integration/pull/1378

### CODE REVIEW

**Comment by mswiderski** [comment]
@jomarko thanks a lot, your PR is now merged here

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by hasys** [comment]
Hi @tsurdilo, @mswiderski, @jomarko,

for me it's OK just notify @evacchi and @jiripetrlik about changes in (Un)Marshaller.

**Comment by evacchi** [comment]
chiming in just to reply to @hasys ping

I will add the following to the documentation.

Current design of the new Marshallers for custom attributes involves [adding a field in an enum-like class called CustomElement](https://github.com/evacchi/kie-wb-common/blob/JBPM-6730/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/CustomElement.java#L28):

```java
public class CustomElement<T> {
  ...
  public static final ElementDefinition<String> description = new StringElement("customDescription", "");
}
```

then adding it to the *Reader, *Writer companions of the corresponding types. 
e.g., let's consider `customDescription` in UserTask

[UserTaskPropertyWriter](https://github.com/evacchi/kie-wb-common/blob/JBPM-6730/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/UserTaskPropertyWriter.java#L87)

```java
public class UserTaskPropertyWriter {
   UserTask task;
   ...
   public void setDescription(String description) {
       CustomInput.description.of(task).set(description);
   }
```

[UserTaskPropertyReader](https://github.com/evacchi/kie-wb-common/blob/JBPM-6730/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/UserTaskPropertyReader.java#L108)

```java
public class UserTaskPropertyReader {
   UserTask task;
   ...
   public String getDescription() {
        return CustomInput.description.of(task).get();
   }
```

**Pull request merged**
