### PR TITLE
[6.5.x] JBPM-6683 - Web designer doesn't generate correct package value

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@hasys pr for https://issues.jboss.org/browse/RHBPMS-4414. thanks

**Comment by mswiderski** [comment]
looks like a back port from master

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@hasys the full stream build error is not related to this, its on Drools and jBPM uber distribution. Since artifacts have still been generated tho you could test if possible? Thanks!

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
tests will be fixed once https://github.com/kiegroup/jbpm/pull/1104 is committed.

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
I have a feeling testing on this won't resume until full downstream build is successful but the jenkins fails have nothing to do with these changes, @hasys could we use the generated bits from full stream build to confirm even tho the full jenkins build fails on something else? thanks.

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
closing since no customer request present for the fix

**Pull request closed without merging**
