### PR TITLE
JBPM-6714 - Designer column sorting in editors should be case insensi…

### PR DESCRIPTION
**Pull request by tsurdilo**
…tive

### CODE REVIEW

**Comment by tsurdilo** [comment]
tests will be fixed once https://github.com/kiegroup/jbpm/pull/1104 is committed.

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by tsurdilo** [comment]
@hasys could you take a look please?

**Comment by tsurdilo** [comment]
@hasys could you take a look please?

**Comment by jomarko** [comment]
@tsurdilo Hi, please could you provide more details, I mean, which columns should sort case insensitively?

**Pull request merged**
