### PR TITLE
JBPM-6599 - Replace all custom string escape methods in jbpm-designer…

### PR DESCRIPTION
**Pull request by tsurdilo**
… with use of StringEscapeUtils.escapeXml

### CODE REVIEW

**Comment by tsurdilo** [comment]
@jomarko can you please take a look? thanks.

**Comment by tsurdilo** [comment]
resolved conflicts after merge of https://github.com/kiegroup/jbpm-designer/commit/357943c7cfd3a525ce794e13c26abf14902a759a

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@jomarko added the tests. thanks!

**Comment by tsurdilo** [comment]
seems jenkins is failing to compile on optaplanner. will try asking jenkins to retest

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
@jomarko i did https://github.com/kiegroup/optaplanner/pull/355 to fix compile issue so hopefully once thats in we can move forward with this pr.

**Comment by tsurdilo** [comment]
Jenkins retest please

**Pull request merged**
