### PR TITLE
JBPM-7827 - REVERT - Wrong link for reusable subprocess in process di…

### PR DESCRIPTION
**Pull request by tsurdilo**
…agram in process definitions

### CODE REVIEW

**Comment by tsurdilo** [comment]
@mswiderski @hasys this reverts the changes for JBPM-7827. needed for JBPM-8255. I will work on removing the link only in generated SVG now.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi Tihomir, sharing my findings:

How it works now:
* During process modelling I am able to open new Editor with Called Element - OK
* In Process Instance I am able to open new window with Called Element downloaded from kie-server - OK (But I found one issue there, see below)
* In Process Definition Called Element is not clickable - OK, according to this [Jira comment](https://issues.jboss.org/browse/JBPM-7827?focusedCommentId=13661010&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13661010)

Chrome and Firefox works fine, IE 11 works partially (2 of 3 points), see below for more details.

### Issues I found:
- When you click on Called Element in Process Instances, new window will be opened with Called Element, but URL will be different (it will always point to `localhost`). When I replaced Localhost by IP Called Element was also displayed. So User should click on Called Element and than manually replace `localhost` by real IP or domain name before he/she will be able to see it. Was it same before?
screenshot from 2019-02-28 18-04-22
- I am not able to open Designer in IE 11. I tested it on master and I can reproduce it there as well. But our tests with Nightly builds for 7.18 branch works as expected. Not sure what is the issue there, will investigate more tomorrow.
image

**Comment by tsurdilo** [comment]
@hasys for issue 1. yes this was working the same way before, nothing changed. I can look into it but maybe better than to raise a new jira ?
for issue 2. yes please let me know what you find. I don't have easy access to IE11 here. Anything in the  browser logs?

**Comment by hasys** [comment]
Update on IE 11 fails.
When I try to open/create Business Process I see this error in IE 11 log:

image

This issue also reproducible for 7.18 as well, it wasn't found earlier since we had an older version of IE on our CI. https://issues.jboss.org/browse/RHPAM-1949

**Pull request merged**
