### PR TITLE
JBPM-6745 - Not possible to download patterns.json and other resource…

### PR DESCRIPTION
**Pull request by tsurdilo**
…s from Project with spaces in name

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @tsurdilo,

thank you for pointing me to this. I think Jozef handl it good. I can image the situation, that you are download patterns.json, append your patterns inside of file and now you will want to upload modified patterns.json back to the global directory. So, in my opinion upload feature is related to our's use case as well as download.

**Comment by tsurdilo** [comment]
@hasys https://issues.jboss.org/browse/AF-934 has been merged now so we could retest this. thanks.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Pull request merged**
