### PR TITLE
JBPM-6405 - On second generation of taskforms some of them disappear …

### PR DESCRIPTION
**Pull request by tsurdilo**
…from library

### CODE REVIEW

**Comment by tsurdilo** [comment]
@pefernan here is the master pr for your Jira you asked about -- there are currently some weird form modeler issues when building workbench master so i will also do a 7.3.x pr for this if its easier for you to test with that.

**Comment by tsurdilo** [comment]
-- on task+process form generation designer no longer deletes then creates a new form asset but updates if form asset already exists. 

-- updated tests as some were useless (testing for old ftl forms only and not doing any real testing )

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
@tsurdilo the code looks well (in fact I did similar changes locally to test it) I'll be testing today.

**Comment by pefernan** [comment]
@tsurdilo the problem build issue is because another PR got merged (https://github.com/kiegroup/jbpm-designer/pull/665) and your code on this PR is not really up to date. Sorry I wasn't expecting that PR being merged so soon.

**Comment by tsurdilo** [comment]
@pefernan sorry what means not up to date? says branch has no conflics so your code should be running alongside this or I'm missing something?

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@pefernan i rebased locally so let's see if this is better now.

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@jsoltes we have the green, would you mind to review?

**Comment by pefernan** [comment]
@jsoltes could you provide the a reproducer?

**Comment by jsoltes** [comment]
@pefernan as always, I am testing on 7.3.x by default. Steps to reproduce:
1. Create process with one human task (no inputs, outputs).
2. Generate all forms - Form Modeler (Preview).
3. Try to open the task taskform.
Expected result: Task opens normally.
Actual result: Instead of openning, you get the error mentioned above.

**Comment by tsurdilo** [comment]
@pefernan @jsoltes I see the same thing -- designer is not doing anything different here. seems like regression on form modeler side . These changes dont affect new form creation as that is still done the same way as before.

**Comment by pefernan** [comment]
@tsurdilo sorry again

**Pull request merged**
