### PR TITLE
GUVNOR-3003: [Library] [Assets list] Order assets alphabetically

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-3003

### CODE REVIEW

**Comment by manstis** [comment]
Part of an ensemble:

- https://github.com/AppFormer/uberfire/pull/697
- https://github.com/kiegroup/kie-wb-common/pull/866
- https://github.com/kiegroup/drools-wb/pull/493
- https://github.com/kiegroup/jbpm-designer/pull/595
- https://github.com/kiegroup/jbpm-form-modeler/pull/105
- https://github.com/kiegroup/optaplanner-wb/pull/163

**Comment by tsurdilo** [comment]
will watch related commit to ask for rebuild - then we can merge

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by tsurdilo** [comment]
jenkins please retest this

**Comment by manstis** [comment]
@tsurdilo None of the ```kiegroup``` PRs are likely to build until AppFormer/uberfire#697 is merged (IIRC Jenkins doesn't cross the ```kiegroup```-```appformer``` boundary when building related PRs).

**Comment by psiroky** [comment]
Jenkins should cross the `appformer` - `kiegroup` boundary. If you think it's not the case, let me know.

I just checked for this PR and it seem the UF PR is being used: `git://github.com/uberfire/uberfire:pull/697/merge:pr697-GUVNOR-3003-merge`

**Comment by tsurdilo** [comment]
@psiroky @manstis yeah it seem that the depends PR is being used. Error is compile error in kie-wb-common/kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-backend/src/main/java/org/kie/workbench/common/forms/editor/backend/indexing/FormDefinitionVisitor.java

**Comment by tsurdilo** [comment]
jenkins please retest this

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@tsurdilo OK with you now?

**Pull request merged**
