### PR TITLE
[DROOLS-2152] fixes after mockito and powermock upgrade

### PR DESCRIPTION
**Pull request by psiroky**
Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/622

### CODE REVIEW

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
need to retest once tests will be fixed once https://github.com/kiegroup/jbpm/pull/1104 is committed

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by psiroky** [comment]
Closing the PR as I won't be able to work on this and there are still some related PRs not completely done. I am keeping the branch around in case someone else would like to pick this up.

**Pull request closed without merging**
