### PR TITLE
JBPM-7827 - Wrong link for reusable subprocess in process diagram in …

### PR DESCRIPTION
**Pull request by tsurdilo**
…process definitions

### CODE REVIEW

**Comment by tsurdilo** [comment]
@mswiderski removes the link ability for reusable subprocess svg

**Comment by mswiderski** [comment]
Jenkins execute full downstream build

**Comment by mswiderski** [comment]
@tsurdilo looks like it removed too much as now it does not work for active process instances as well. I think we need to have a link but it should be no op so to say by default. Then when we annotate the diagram with active instances we add the link to sub process instance if we have it - but that should be more of enabling the location of the link. See here https://github.com/kiegroup/droolsjbpm-integration/blob/master/jbpm-process-svg/src/main/java/org/jbpm/process/svg/model/SetSubProcessLinkTransformation.java#L36

**Comment by tsurdilo** [comment]
@mswiderski @LuboTerifaj sorry about that -- added the link back in the svg element of the node. thanks!

**Comment by mswiderski** [comment]
Jenkins execute full downstream build

**Comment by mswiderski** [comment]
this downstream build does not have kie-wb at all ... no idea what happened... retrying

**Comment by mswiderski** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@mswiderski i was worried about what @LuboTerifaj found in last comment. In order to make this not linkable inside designer I have to remove the link, but its needed for active instances svg. Not sure what to do about this - any ideas ?

**Comment by tsurdilo** [comment]
@mswiderski updated now it should have link:

<a id="pimg" onclick="javascript:void(0);"> .... </a>

here is sample svg if you need: https://gist.github.com/tsurdilo/e7a9a3fb2458e5ad85435935b470c339

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by mswiderski** [comment]
@tsurdilo it still does not work as expected, at least for the OrderIT sample case project. When you look at the generated sag (and I did remove the sag from the project and change process a bit and saved it to regenerate the svg) it has this tag for pimg

```
<a id="_880F62E8-25BC-4792-919D-97E33BC441E1pimg" onclick="javascript:void(0);" xlink:href="">
```
the problem is because of the xlink:href attribute, once this is removed it all works fine. Could you please make sure that is not generated?

**Comment by tsurdilo** [comment]
@mswiderski sorry about that - updated and the empty xlink:href is no longer generated. for sample svg from workbench see here: https://gist.github.com/tsurdilo/8995b21c3d92bc3ea1f5a5a5c20c8886

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
There is still missing workbench war.

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Pull request merged**
