### PR TITLE
[7.0.x] JBPM-5875 - Not possible to change a value of task assignment

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@hasys can you review please? Thanks.

**Comment by manstis** [comment]
This isn't in the 7.0.0.Final "agreed" list.. could you please have @krisv confirm this should be on 7.0.x?

**Comment by manstis** [comment]
7.0.0.Final filter https://issues.jboss.org/browse/JBPM-5895?filter=12331527

**Comment by tsurdilo** [comment]
@krisv @manstis Hello Kris, this fixes a pretty big issue that affects 7.0.x as well. I think it should be included but not my call of course.

**Pull request merged**
