### PR TITLE
Removing redundant properties files

### PR DESCRIPTION
**Pull request by Rikkola**
This _en i18n file contains the same content as the default one.

### CODE REVIEW

**Comment by manstis** [comment]
@Rikkola same commemt as on your other similar PR.

**Comment by Rikkola** [comment]
Ok. Let's ask @tsurdilo he added this file and might remember the cause.

@tsurdilo There is some redundancy in the Constants files. The default and _en are covering the same scenarios. Do you remember if there was a reason to do this?

**Comment by tsurdilo** [comment]
@Rikkola im removing it in this pr so maybe this one no longer needed: https://github.com/kiegroup/jbpm-designer/pull/763

**Comment by Rikkola** [comment]
@tsurdilo Ok, thanks for the information. I think we should use `copy-rename-maven-plugin` also in kie-wb-distributions, if it is not already used. I'll take a look.

**Pull request closed without merging**
