### PR TITLE
JBPM-6088 - Not possible to run Simulation of process with Send Task

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@hasys this is not ready yet - i found more issues during testing

**Comment by tsurdilo** [comment]
@hasys this pr is good for designer alone. When run in workbench however this pr is also needed:
https://github.com/kiegroup/kie-wb-common/pull/931

this depends on https://github.com/kiegroup/kie-wb-common/pull/931 to also be merged to fully work

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
updated kie-wb-commons pr: https://github.com/kiegroup/kie-wb-common/pull/932

**Pull request merged**
