### PR TITLE
[6.5.x] JBPM-6653 - Use real defaults contents on new project creation - fix …

### PR DESCRIPTION
**Pull request by tsurdilo**
…for tomcat

### CODE REVIEW

**Comment by mbiarnes** [comment]
@jhrcek can you please review and approve this (you are the suggested reviewer :) si this can be mergen and I suppose 6.5.x will build

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
I've no idea what this issue is about or how to test it. @tsurdilo Do you have any instructions how to test this on tomcat? Alternatively reassign this for review to someone else, please :)

**Comment by mbiarnes** [comment]
@jhrcek sorry Jan if I selected you by mistake as Reviewer - I want that this commit gets merged today so that the 6.5.x daily build doesn't fail

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@mbiarnes @jhrcek do we need full build to merge this since it has been approved? 
@jhrcek yes sorry the way I tested this is build jbpm-designer and kie-workbench and deploy per instructions in the workbench war on tomcat 7. 
I did the same for the master and 7.5.x prs on tomcat 8 so @jhrcek could you maybe also approve those so they can all be merged together? Thanks!

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@tsurdilo can't this be merged? kie dailyBuild 6.5.x is still failing (last successful build was 30th November)

**Comment by tsurdilo** [comment]
@mbiarnes yes it can I was waiting for someone to tell me that its ok. Will merge.

**Pull request merged**
