### PR TITLE
JBPM-8124: Remove legacy process designer from the asset list. 

### PR DESCRIPTION
**Pull request by inodeman**
@romartin Can you check this PR?

### CODE REVIEW

**Comment by inodeman** [comment]
This change adds authorization manager and session info to the legacy designer, so that it can be enabled/disabled in Permissions. It is related to 2 PRs(https://github.com/kiegroup/kie-wb-distributions/pull/950,  https://github.com/kiegroup/kie-wb-common/pull/2798)

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
missing @hasys @tsurdilo reviews

**Comment by tsurdilo** [comment]
Why is this needed in designer. Why would you break this project in order to remove it from the workbench? Just remove it from the workbench :)

**Comment by hasys** [comment]
Hi @tsurdilo,

jbpm designer is not removed from the Business Central, but rather disabled. So user have a chance to reenable it if needed.

**Pull request closed without merging**
