### PR TITLE
[AF-913]: Changed category to BPMN Type Definition.

### PR DESCRIPTION
**Pull request by adrielparedes**
Related Issues:

https://github.com/kiegroup/appformer/pull/116
https://github.com/kiegroup/kie-wb-common/pull/1317
https://github.com/kiegroup/drools-wb/pull/727
https://github.com/kiegroup/jbpm-designer/pull/728

### CODE REVIEW

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by tsurdilo** [comment]
tests will be fixed once https://github.com/kiegroup/jbpm/pull/1104 is committed.  Sorry for the inconvenience.

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by cristianonicolai** [comment]
Reverting commit as dependant PRs are not yet approved/merged.

**Comment by adrielparedes** [comment]
@cristianonicolai can you reopen this issue please? I don't have permissions to do that.

**Comment by cristianonicolai** [comment]
@adrielparedes I believe you need to open a new PR unfortunately.

**Pull request merged**
