### PR TITLE
[6.5.x] JBPM-6274 - Update batik to 1.9 for 6.5.x

### PR DESCRIPTION
**Pull request by tsurdilo**
This requires some more updated to droolsjbpm-build-bootstrap that @mbiarnes  will do.

### CODE REVIEW

**Comment by tsurdilo** [comment]
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/486#pullrequestreview-52759672

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @tsurdilo,

for correct work of full downstream build with multiple PRs on different repository you need to set the same name for all branches you are sending to PR. For example for this PR: 
- tsurdilo  wants to merge 1 commit into kiegroup:6.5.x from tsurdilo:**JBPM-6274-6.5.x-new**
It means that in other repository PR has to look like:
- tsurdilo  wants to merge 1 commit into kiegroup:6.5.x from mbiarnes:**JBPM-6274-6.5.x-new**

@psiroky please correct me if I wrong (also question: is it possible to use the same branch name if PRs coming from different users?).

P.S. for this PR it is not actual any more because second PR is already merged.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins retest please

**Comment by mswiderski** [comment]
@tsurdilo @hasys there is a version issue in droolsjbpm-integration that most likely is causing this build to fail, I just sent PR to fix it there https://github.com/kiegroup/droolsjbpm-integration/pull/1081

**Comment by psiroky** [comment]
Both username and branch name need to match. We may reconsider this, but it could cause certain level of confusion if PRs from different people were matched together (especially when some people do not use feature branches and create PRs directly from their master or 6.5.x branches).

**Comment by mbiarnes** [comment]
After the PRs of droolsjbpm-build-bootstrap and droolsjbpm-integration are merged this should build now.
Jenkins please retest this

**Comment by tsurdilo** [comment]
@psiroky @hasys sure I am aware of the branch names on multiple commits across modules, in this case multiple people were committing and we did not match branch names. that's easier done when you have a single person doing it. I think we should be ok now as Michael mentioned in last comment. Thanks.

**Comment by mbiarnes** [comment]
@tsurdilo can you please merge this?

**Comment by psiroky** [comment]
I actually tried to upgrade to newer batik years ago. See https://github.com/kiegroup/jbpm-designer/pull/50. It never happened as presumably there was lots of changes required. Direct quote from @tsurdilo:

> We upgraded to 1.6.1 recently which fixed the vulnerability issues with batik 1.6. Moving to 1.7 requires a good amount of rewrites in Designer which I don't think should be done unless a move to 1.7 is absolutely needed.

Did something changed with 1.9? Are we sure this will upgrade will not break the designer?

**Comment by tsurdilo** [comment]
@psiroky yes that was true because with 1.7 and now 1.9 we used to use fop for PDF generation and this even would not be possible but not too long ago we removed the dependency of fop for PDF generation and the upgrade is possible now. Sorry I forgot to mention this when we no longer started using fop . Thanks.

**Comment by psiroky** [comment]
@tsurdilo great, thanks for the details.

**Pull request merged**
