### PR TITLE
[7.0.x] RHBPMS-4704 and JBPM-5988 - Designer have no button to exit from full screen

### PR DESCRIPTION
**Pull request by tsurdilo**
this also fixes JBPM-5986

### CODE REVIEW

**Comment by tsurdilo** [comment]
@hasys @jsoltes could you guys review? Thanks!!

**Comment by hasys** [comment]
jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
7.0.0.Final is currently being built by @mbiarnes 

I guess this PR is simply closed!?

**Comment by tsurdilo** [comment]
@manstis @hasys ok sounds good i will close this pr then. thanks!

**Pull request closed without merging**
