### PR TITLE
JBPM-6794 - Invalid content was found starting with element caused by…

### PR DESCRIPTION
**Pull request by tsurdilo**
… 'documentation' ordering

### CODE REVIEW

**Comment by tsurdilo** [comment]
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/688

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Hi, I will have a look at it tomorrow, please do not merge it yet.

**Comment by tsurdilo** [comment]
@LuboTerifaj sure. you need to apply kiegroup/droolsjbpm-build-bootstrap#688 first locally and build before testing

**Comment by tsurdilo** [comment]
@LuboTerifaj were you able to do your testing?

**Comment by LuboTerifaj** [comment]
@tsurdilo yes I was, but I found probably regression. When click on Documentation in SequenceFlow, wrong dialogue window appears. See comment in Jira.

**Comment by tsurdilo** [comment]
@LuboTerifaj you actually found a bug that has nothing to do with this pull request. I will amend with fix here as its small

**Comment by tsurdilo** [comment]
@LuboTerifaj amended with small fix for your find.

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Thank you for the fix. It is ok now.

**Pull request merged**
