### PR TITLE
JBPM-5984 - Workbench notify twice about broken Process

### PR DESCRIPTION
**Pull request by tsurdilo**
Correctly displays the notification now

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@manstis good point. i will create a jira to remove this class and just delegate. I believe this might have been added in early stages of integration with workbench where either a common service did not exist or i did not know about it. Either way I'll handle it in a new jira if thats ok. Thanks.

**Comment by tsurdilo** [comment]
@manstis oh and i removed the iocmanager code from the class too per your request . thanks.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@hasys that is weird because i am not getting the same --- https://streamable.com/y96wh

**Comment by tsurdilo** [comment]
@hasys no problem at all - so are we good to merge (could you approve?) thanks!

**Pull request merged**
