### PR TITLE
JBPM-6405 - On second generation of taskforms some of them disappear from library

### PR DESCRIPTION
**Pull request by alessioscalici**
**WARNING** To be merged with https://github.com/kiegroup/kie-wb-common/pull/1223

This PR changes are the same as https://github.com/kiegroup/jbpm-designer/pull/672, pointing to 7.3.x

@pefernan @jsoltes FYI

### CODE REVIEW

**Comment by pefernan** [comment]
@tsurdilo this PR is a copy of your PR (https://github.com/kiegroup/jbpm-designer/pull/670). @alessioscalici has fixed the forms issue we found on kie-wb-common and created it to make sure that jenkins full downstream build takes both changes.

**Comment by pefernan** [comment]
DO NOT MERGE PLEASE

**Comment by tsurdilo** [comment]
@alessioscalici @pefernan 

Sorry -1 from me here - copying someones pr just to get jenkins full build to run I think is not necessary here.
If your kiegroup/kie-wb-common#1223 has a test with it, just get that merged then re-test the actual prs on this that were submitted. @mswiderski wdyt on this?

**Comment by alessioscalici** [comment]
@tsurdilo please don't take it personally, I don't want to steal your work
taking credits on what you did, nor to be disrespectful in any way. I just
needed your changes it to get the builds to work.

Il 06 ott 2017 21:12, "Tihomir Surdilovic" <notifications@github.com> ha
scritto:

**Comment by pefernan** [comment]
@tsurdilo sorry if you feel bad about this, I asked @alessioscalici to send this PR to make it easy with the jenkins build, I never wanted to have a problem with you. 

As I said again on IRC, sorry for this. I promise that next time all talk to you before.

**Pull request closed without merging**
