### PR TITLE
JBPM-6677 - Designer generates invalid task I/O when you open a proce…

### PR DESCRIPTION
**Pull request by tsurdilo**
…ss with task I/O containing underscore

### CODE REVIEW

**Comment by tsurdilo** [comment]
@hasys project jira for https://issues.jboss.org/browse/RHBPMS-5077 - could you please review? Thanks

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@hasys are we ok on this? thanks

**Pull request merged**
