### PR TITLE
JBPM-8297 - It is not possible to open Designer in latest IE 11

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
Hi @hasys  would you mind testing locally with this update of jquery? This is a pretty hard one to figure out as i dont have access to latest IE 11 locally. Hope this jquery update fixes issues as there are some already filed and fixes jquery bugs like https://bugs.jquery.com/ticket/14081 and we use really old jquery in designer.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @tsurdilo,

jquery looks updated but, designer still doesn't load:
image
image

I cleared all caches but with no luck.

**Comment by hasys** [comment]
UPD:

Looks like designer still has old jquery libraries in the lib folder, see `workbench.war/org.kie.bc.KIEWebapp/lib` folder
image

Also IE 11 fails with `designer-lib.js` but this script declared BEFORE new version of `jquery-1.10.2`:
image

So `designer-lib` doesn't use `jquery` or uses older version which imported somewhere else.

**Comment by tsurdilo** [comment]
@hasys hi, i updated prototype js lib as well where this error seems to be happening. do you mind testing again as i am still trying to set up old laptop to run latest windows.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @tsurdilo,

now I see different issue: 
image

It is still not possible to load and now event panels and canvas didn't show up.

Don't sure what this new issue mean, but according to [this](https://stackoverflow.com/questions/15360918/xml5619-incorrect-document-syntax-error-in-ie10-only) article it can be related to content-type. I did screenshots of missing content types and 404 errors.
image
image

I tried to switch to Overview, open Project Explorer, Select Latest Version, full-screen mode, but nothing helped.
image

**Comment by hasys** [comment]
**IMPORTANT UPD**

With latest changes in this PR designer is not broken on IE 11 only, now I am not able to open Designer in any browser (tested with Chrome and Firefox).

**Comment by tsurdilo** [comment]
@hasys ok ill revert the latest change and try again

**Comment by romartin** [comment]
@tsurdilo @hasys @lazarotti lemme know guys when this is ready to test, cause as far as I see on comments above it's still not working properly

**Comment by tsurdilo** [comment]
will close this pr and add a new one as after @hasys further investigation in email this seems to be issue with data io editor

**Pull request closed without merging**
