### PR TITLE
JBPM-6661 - Sorting of 'Called Element' in reusable subprocess is alw…

### PR DESCRIPTION
**Pull request by tsurdilo**
…ays disabled

### CODE REVIEW

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by jomarko** [comment]
@tsurdilo thanks for the PR, the full downstream build failed, however artifacts were generated. I tried the build and the called elements can be sorted. However I have question, I downloaded also the latest 7.5.0 community snapshot and I don't see difference in the behavior. Could you please please guide me how to see this fix works? In another words what was the behavior before and after? Thanks in advance.

**Comment by tsurdilo** [comment]
@jomarko sure thing. in your process if you add a "reusable subprocess" and in its properties select "called element" you will see the editor displaying all other found processes. This editor has two colums "process id" and "package name". If you click on the little down arrow on the column headers it will show the sorting options. Before all these options were disabled. With this change, they should enabled like this (clear your browser cache to make sure you get the updated js):

screen shot 2017-12-04 at 9 09 48 am

**Comment by tsurdilo** [comment]
@jomarko there is an image on the jira https://issues.jboss.org/browse/RHBPMS-5070 which has attached image on how the sorting options are not enabled before this change.

**Comment by tsurdilo** [comment]
@jomarko thanks! could you do same for https://github.com/kiegroup/jbpm-designer/pull/707 pls ? thanks.

**Pull request merged**
