### PR TITLE
[6.5.x] RHBPMS-4699 - [GSS](6.4.z) Copy&Paste activities between different processes does not work properly in BPM Suite 6.4.x

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@krisv 6.5.x port of jira - anyone that could approve?

**Comment by krisv** [comment]
@tsurdilo I suggest you ask your QE contact to take a look and approve

**Comment by tsurdilo** [comment]
@krisv i have asked QE in the JIRA. Thanks.

**Comment by jhrcek** [comment]
@tsurdilo designer is @hasys 's area of expertise, reassigning to him to check this.

**Comment by hasys** [comment]
@tsurdilo, @jhrcek only Lukas and Radek can ACK issues. And as I can see it is already ACKed.

**Pull request merged**
