### PR TITLE
[7.0.x] RHBPMS-4704 - fix to ask for view to resize after full screen mode

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@jlindop this fixes the issue you saw sometimes where the designer frame does not resize after full screen is enabled.

**Comment by tsurdilo** [comment]
jenkins please retest this

**Comment by tsurdilo** [comment]
@jlindop ready to review

**Comment by manstis** [comment]
@jlindop @tsurdilo @etirelli says only critical items should go into 7.0.x now... is this critical?

**Comment by jlindop** [comment]
@manstis Thanks for the reminder. No, it's not critical.

**Comment by tsurdilo** [comment]
@manstis @jlindop is ok now to merge?

**Comment by manstis** [comment]
@tsurdilo Has it become more critical now then?

**Comment by tsurdilo** [comment]
@manstis i'm not sure how to answer that question honestly.
This is for a platform Jira just like RHBPMS-4704 (https://github.com/kiegroup/jbpm-designer/commit/db1a4e5a65a24babc0fdea02bc17bd494ee9e168) which we merged into 7.0.x on Apr. 24th. This PR was done at the same time so why one is/was more urgent than the other I have no idea.

**Comment by jlindop** [comment]
@tsurdilo I think it's a case of timing. The previous commit made it into the 7.0.0.CR2 release, but this one has missed that release. Maybe check with Kris on whether this fix should go into the 7.0.x branch now.

**Comment by etirelli** [comment]
@krisv your call, should this be merged?

**Comment by krisv** [comment]
I don't think this is critical for 7.0.0.Final, so I suggest to put the fix on master only (which we willo move to right after 7.0.0.Final relaese anyway).

**Comment by tsurdilo** [comment]
ok i will close this pr then. thanks @krisv

**Pull request closed without merging**
