### PR TITLE
JBPM-6025 - Update designer navbar

### PR DESCRIPTION
**Pull request by tsurdilo**
Designer navbar updates:
* removed all icons from navbar -- icons were not updated for years, not all items had icons, did not bring any value to user / were confusing
* grouping of nav functions in user-friendly groups - groups : File, Edit, Arrange, Tools, View, Validate, Import/Export, Forms, Services, Themes much easier to understand than before
* "toggle" items like full-screen mode have a check mark now so users can easily see if enabled/disabled
* removed toolbar description hover - most of descriptions were exactly the same as the item text and did not bring any value
* disabled add/remove docker as the functionality needs to be fixed -- https://issues.jboss.org/browse/JBPM-6131

### CODE REVIEW

**Comment by tsurdilo** [comment]
screen shot 2017-06-20 at 10 51 03 pm

**Comment by tsurdilo** [comment]
@hasys could you please review - thanks!

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
we decided that this would not be included in designer now. maybe it could come back at some later point if there is time/resources

**Pull request closed without merging**
