### PR TITLE
[6.5.x] JBPM-7382 - Process model SVG is not updated in Windows environments

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
@krisv, @triceo 
Do we want have this one in 6.5.x? If yes, can you put acks to the Jiras ([RHBPMS-5187](https://issues.jboss.org/browse/RHBPMS-5187), [RHBPMS-5188](https://issues.jboss.org/browse/RHBPMS-5188)) please?
Thanks.

**Comment by tsurdilo** [comment]
@LuboTerifaj Kris told me to do the 6.5.x pr for it. Will check with him and if ok will close this PR. thanks

**Comment by tsurdilo** [comment]
@krisv Hi, do we still need this 6.5.x pr or can it be dropped as stated above?

**Pull request closed without merging**
