### PR TITLE
[7.3.x] JBPM-6405 - On second generation of taskforms some of them disappear …

### PR DESCRIPTION
**Pull request by tsurdilo**
…from library

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@jsoltes here too i think that it has not to do with this pr. The code that generates a new form same as before (inputs or not). Seems issue with form creation @pefernan ?

**Comment by pefernan** [comment]
@tsurdilo sorry again

**Comment by pefernan** [comment]
@tsurdilo  could you please provide this PR for 7.4.x branch?

**Comment by tsurdilo** [comment]
@pefernan do we need 7.4.x pr for this? After the meet today im not sure if we should -- @kris wdyt?

**Comment by pefernan** [comment]
@tsurdilo we do need it for 7.4 too. Thank you

**Pull request merged**
