### PR TITLE
[AF-913]: Changed category to BPMN Type Definition

### PR DESCRIPTION
**Pull request by adrielparedes**
https://github.com/kiegroup/appformer/pull/116
https://github.com/kiegroup/kie-wb-common/pull/1317
https://github.com/kiegroup/drools-wb/pull/727
https://github.com/kiegroup/jbpm-designer/pull/732
https://github.com/kiegroup/kie-wb-distributions/pull/664

### CODE REVIEW

**Comment by tsurdilo** [comment]
@adrielparedes can this be merged?

**Comment by adrielparedes** [comment]
@tsurdilo We have to wait that the others PR are approved, I think monday morning.

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@adrielparedes can this be merged?

**Comment by jhrcek** [comment]
@tsurdilo please don't merge yet. There are still some not addressed comments in other PRs of this ensemble.

**Comment by tsurdilo** [comment]
@jhrcekI have added "don't merge yet" to the title of the pr just in case. Please remove that part of title when it's ready if you can . Thanks!

**Comment by adrielparedes** [comment]
Jenkins execute full downstream build

**Comment by adrielparedes** [comment]
jenkins retest this

**Pull request merged**
