### PR TITLE
[7.5.x] JBPM-6677 - Designer generates invalid task I/O when you open a proce…

### PR DESCRIPTION
**Pull request by tsurdilo**
…ss with task I/O containing underscore

### CODE REVIEW

**Comment by tsurdilo** [comment]
@hasys project jira for https://issues.jboss.org/browse/RHBPMS-5077 - could you please review? Thanks

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by mswiderski** [comment]
same here, is this needed for BRMS?

**Comment by jsoltes** [comment]
@mswiderski @tsurdilo This fix should be merged also to 7.5.x, since human tasks are also available in RHDM. Another reason is that with RHDM GA we are also testing RHBA GA in parallel (this also is how this bug was discovered), so it makes sense also fixing the RHBA in 7.5.x

**Comment by mswiderski** [comment]
@jsoltes what do you mean by this:

> since human tasks are also available in RHDM

I don't think that user tasks are available in RHDM ... unless I don't know what RHDM is ... User tasks require complete jBPM to be configured including data base etc.

**Comment by jhrcek** [comment]
@mswiderski @tsurdilo  there's a [regression](https://issues.jboss.org/browse/RHBA-108) in designer reported for this  since 2 prod releases ago, so instead of reopening this, that one should be fixed instead.

**Comment by jsoltes** [comment]
@mswiderski jhrcek's comment explains why I thought it is there (I just checked the library in the designer not knowing it is a bug). Still the second reason remains - we are testing RHBA in parallel with RHDM, so for the sake of faster feedback on the product quality it makes sense to include fixes for RHBA in 7.5.x, too.

**Pull request closed without merging**
