### PR TITLE
JBPM-8297 - It is not possible to open Designer in latest IE 11

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @tsurdilo, unfortunately, this PR didn't help as well. I tried it with `-Ddesigner.useolddataassignments=true` property as well, but with no luck. I was able to open old data assignments editor in Chrome, but IE 11 still fails with same issue.

**Comment by tsurdilo** [comment]
@hasys ok. i will update this pr soon with another fix..which should go along with the Ddesigner.useolddataassignments=true property

**Comment by tsurdilo** [comment]
@hasys updated -- this should be the "official" fix for this jira. sorry took so long.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
can you aprove this PR @hasys ? we need to merge it today to get into today's tag

**Comment by mareknovotny** [comment]
@mbiarnes fyi, this is waiting for merging into our tag too

**Comment by mareknovotny** [comment]
Backport to 7.18.x https://github.com/kiegroup/jbpm-designer/commit/fc0ebb0ef2b74ff0b52b900cb5ca1cac3fe11639 was committed before this PR merged

**Pull request merged**
